# RL parameters
batch_size: 128
gamma: 0.999
eps_start: 0.9
eps_end: 0.05
eps_decay: 200
target_update: 10
stopping_metric:
  type: shape
  level: 2.5

# Environment parameters
aggregation: 1 min
n_samples: 100
fx_pair: EURUSD
tech_indicators:
  macd: [12,26]
  rsi: [14]
  adx: [14,14]
actions:
  - long
  - neutral
  - short
pip_size:
  AUDJPY: 0.0001
  AUDNZD: 0.0001
  AUDUSD: 0.0001
  CADJPY: 0.01
  CHFJPY: 0.01
  EURCHF: 0.0001
  EURGBP: 0.0001
  EURJPY: 0.01
  EURUSD: 0.0001
  GBPJPY: 0.01
  GBPUSD: 0.0001
  NZDUSD: 0.0001
  USDCAD: 0.0001
  USDCHF: 0.0001
  USDJPY: 0.01

# Model parameters
memory: 100000
learning_rate: 0.001
dense_params:
  - {out_features : 256, dropout : 0.5}
  - {out_features : 128, dropout : 0.5}
conv_params:
  - {out_channels : 64, kernel_size: 4}
  - {out_channels : 32, kernel_size: 2}