# RL parameters
batch_size: 16
gamma: 0.999
eps_start: 0.9
eps_end: 0.05
eps_decay: 200
target_update: 100
max_steps: 10000
stopping_metric:
  type: sortino
  threshold: 2.0

# Environment parameters
aggregation: 1 hour
n_samples: 100
fx_pair: EURUSD
neutral_cost: 0
tech_indicators:
  macd: [12,26]
  rsi: [14]
  # adx: [14,14]
actions:
  - long
  - neutral
  - short
pip_size:
  AUDJPY: 0.0001
  AUDNZD: 0.0001
  AUDUSD: 0.0001
  CADJPY: 0.01
  CHFJPY: 0.01
  EURCHF: 0.0001
  EURGBP: 0.0001
  EURJPY: 0.01
  EURUSD: 0.0001
  GBPJPY: 0.01
  GBPUSD: 0.0001
  NZDUSD: 0.0001
  USDCAD: 0.0001
  USDCHF: 0.0001
  USDJPY: 0.01

# Model parameters
memory: 1000
start_memory: 100
learning_rate: 0.001
dense_params:
  - {out_features : 2048}
  - {out_features : 2048}
conv_params:
  - {out_channels : 512, kernel_size: 1}
  - {out_channels : 512, kernel_size: 1}
  - {out_channels : 512, kernel_size: 1}
  - {out_channels : 512, kernel_size: 1}
  - {out_channels : 512, kernel_size: 1}
  - {out_channels : 512, kernel_size: 1}
  - {out_channels : 512, kernel_size: 1}
  - {out_channels : 512, kernel_size: 1}
  - {out_channels : 512, kernel_size: 1}
  - {out_channels : 512, kernel_size: 1}
