python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_8.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_7.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_45.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_57.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_10.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_41.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_0.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_37.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_63.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_30.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_2.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_23.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_4.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_11.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_25.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_14.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_62.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_48.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_29.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_52.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_34.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_15.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_16.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_3.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_13.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_20.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_50.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_42.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_12.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_19.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_18.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_51.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_33.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_26.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_38.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_31.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_21.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_60.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_24.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_61.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_39.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_40.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_54.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_32.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_22.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_6.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_58.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_47.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_1.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_9.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_56.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_49.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_27.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_28.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_35.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_17.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_36.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_53.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_46.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_55.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_5.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_59.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_44.yaml
python /home/nabs/Projects/forex_rl/src/main.py --config_path /home/nabs/Projects/forex_rl/config/config_43.yaml
