actions:
- long
- neutral
- short
aggregation: 1 min
batch_size: 128
conv_params:
- kernel_size: 6
  out_channels: 128
- kernel_size: 4
  out_channels: 64
- kernel_size: 2
  out_channels: 32
dense_params:
- out_features: 4096
- out_features: 4096
- out_features: 4096
- out_features: 4096
eps_decay: 200
eps_end: 0.05
eps_start: 0.9
fx_pair: EURUSD
gamma: 0.999
learning_rate: 1.0e-05
max_steps: 5000
memory: 10000
n_samples: 100
neutral_cost: -500
pip_size:
  AUDJPY: 0.0001
  AUDNZD: 0.0001
  AUDUSD: 0.0001
  CADJPY: 0.01
  CHFJPY: 0.01
  EURCHF: 0.0001
  EURGBP: 0.0001
  EURJPY: 0.01
  EURUSD: 0.0001
  GBPJPY: 0.01
  GBPUSD: 0.0001
  NZDUSD: 0.0001
  USDCAD: 0.0001
  USDCHF: 0.0001
  USDJPY: 0.01
start_memory: 1000
stopping_metric:
  threshold: 2.0
  type: sortino
target_update: 100
tech_indicators:
  macd:
  - 12
  - 26
  rsi:
  - 14
